# Generated by Django 4.1.1 on 2022-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
